apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-service
  template:
    metadata:
      labels:
        app: node-service
    spec:
      containers:
        - name: node-container
          image: <your_ecr_url>/node-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: node-config
                  key: NODE_ENV
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: node-secret
                  key: SECRET_KEY
